
{% set name = "fdupes" %}
{% set version = "2.0.0" %}
{% set sha256 = "7d2bddee297b6780547ce7f4f6a9e045cae90b763f64cf971b558f0374ec8909" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/adrianlopezroche/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - fdupes --version

about:
  home: https://github.com/adrianlopezroche/fdupes
  license: MIT
  license_family: MIT
  license_file: README
  summary: Identify or delete duplicate files
  description : |
    FDUPES is a program for identifying or deleting duplicate files residing
    within specified directories.
  dev_url: https://github.com/adrianlopezroche/fdupes

extra:
  recipe-maintainers:
    - keuv-grvl
