{% set name = "fdupes" %}
{% set version = "2.2.1" %}
{% set sha256 = "7d12e9d28c6a5dc46ff3a37fafd65b4b84f5c19dddf630beec8d67bc158fa265" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/adrianlopezroche/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - fdupes --version

about:
  home: https://github.com/adrianlopezroche/fdupes
  license: MIT
  license_family: MIT
  license_file: README
  summary: Identify or delete duplicate files
  description: |
    FDUPES is a program for identifying or deleting duplicate files residing
    within specified directories.
  dev_url: https://github.com/adrianlopezroche/fdupes

extra:
  recipe-maintainers:
    - keuv-grvl
