travis:
  secure:
    BINSTAR_TOKEN: mNRPCVlOm9o6q9+E881tdt7Nrn5Ij3BPv27Y+OTJr5TpEdxcl+jkq0ZSTbcn6nuDDbSYMc0YQ0haticIRwsEnlAYmemCCTCP6g0b/qgM3G8Qgpje7oI9qPZajFsbna+e8vALm8KSKkO0u/XZoVBpXGuOZSSPVZsGWDr0QIK5sUol2qUBgjALiePn9MhuuQLNSri7GDX8Xzj+G4BVKZ3XjV2TGAelKvAIQcgdSOOcXOq7eHQZ17pblSWknqPH5D4405EHoQYxFws/Y/HH7fTdV/UNGkheprISrXiJpG4BHEyJur/mGd8VbJiEy6MvE1gZj8EQ+9dYcEi/19pHyeGSL58GqDgjoJrYDCp0HkYxDD8HPCr1g70mXyYjeTYunlWevNDNk4Wpp0HvK5PrmsvHcKzcczwLr4oo6jKNNMvHQd9bQ8zWLWJyNyhklvNBT1igrnyrjg+Aq7ShBYsvHvmB2P2mGL/y6byZA/jN+5+GWjZ8NrtHQbLwneulBZe5s0XvP1EP8BQRNvFfu3URMW0CJkIxKxfFhiyCR5i2lBpYexxaPjGYAObFacR/sgvLk8FxRstSLD16ZybkJTdP1kH3mFzgiIrLPxCeZbPAaRROvpzUep5Uqg2BvM54aUHrVoWZ16R5Qps6WIqAOFWRi7fMNXWH6G1XAwMaRqS3RKOuZXw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
